"""Initial migration.

Revision ID: 57997dc8695f
Revises: 
Create Date: 2024-04-17 06:28:38.775846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57997dc8695f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_recipes_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_bookmarks_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_bookmarks_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('1 <= rating AND rating <= 5', name='rating_range'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_reviews_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_reviews_user_id_user_profiles')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('bookmarks')
    op.drop_table('recipes')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
